name: CI/CD Workflow

on:
  push:
    branches:
      - development

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Backend Tests
      - name: Set up Node.js (Backend)
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use the version of Node.js you're working with

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Run backend tests
        run: |
          cd backend
          npm test # Make sure this command runs your backend tests

      # Frontend Tests
      - name: Set up Node.js (Frontend)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Run frontend tests
        run: |
          cd frontend
          npm lint # Make sure this command runs your frontend tests

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy or Build (optional)
        run: |
          # Add deployment or build steps if needed
          #echo "Deployment or Build Step"
          npm build

  push-to-main:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: development  # Checkout the latest code from development branch

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Push to main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout main
          git merge development --no-ff
          git push origin main
