name: CI/CD Workflow

on:
  push:
    branches:
      - development

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all branches and history

      # Backend Tests
      - name: Set up Node.js (Backend)
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use the version of Node.js you're working with

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Run backend tests
        run: |
          cd backend
          npm test # Make sure this command runs your backend tests

  push-to-main:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all branches and history

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Ensure main branch exists
        run: |
          # Check if main exists, if not, create it
          if ! git show-ref --verify --quiet refs/heads/main; then
            git checkout -b main
            git push origin main
          else
            git checkout main
          fi

      - name: Merge development into main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git merge development --no-ff
          git push origin main
