name: CI/CD Workflow

on:
  push:
    branches:
      - development

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grant necessary permissions to push changes
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all branches and history

      # Backend Tests
      - name: Set up Node.js (Backend)
        uses: actions/setup-node@v3
        with:
<<<<<<< HEAD
          node-version: "18" # Use the version of Node.js you're working with
=======
          node-version: '18'
>>>>>>> 993c25bf121452477ac0971b0cbcce650ec1fc06

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Run backend tests
        run: |
          cd backend
          npm test

  push-to-main:
    runs-on: ubuntu-latest
    needs: build-and-test
<<<<<<< HEAD
=======
    permissions:
      contents: write
>>>>>>> 993c25bf121452477ac0971b0cbcce650ec1fc06
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
<<<<<<< HEAD
          fetch-depth: 0 # Fetch all branches and history
=======
          fetch-depth: 0
>>>>>>> 993c25bf121452477ac0971b0cbcce650ec1fc06

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Ensure main branch exists
        run: |
          # Check if main exists, if not, create it
          if ! git show-ref --verify --quiet refs/heads/main; then
            git checkout -b main
            git push origin main
          else
            git checkout main
          fi

      - name: Pull latest changes from main
        run: |
          git pull origin main

      - name: Merge development into main
        run: |
          git merge development --no-ff

      - name: Push merged changes to main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main
